#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AncientIconSet.Resource", IsApplication=true)]

namespace AncientIconSet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic00 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic01 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic02 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic03 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic04 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic05 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic06 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic07 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic08 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic09 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic10 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic11 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic12 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic13 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic14 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic15 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic16 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic17 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic18 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic19 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic20 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic21 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic22 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic23 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic24 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic25 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic26 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic27 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic28 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic29 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic30 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic31 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic32 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic33 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic34 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic35 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic36 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic37 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic38 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic39 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic40 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic41 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic42 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic43 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic44 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic45 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic46 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic47 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic48 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic49 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic50 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic51 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic52 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic53 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic54 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic55 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic56 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic57 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic58 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic59 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic60 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic61 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic62 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic63 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic64 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic65 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic66 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic67 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic68 = 2130837572;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int kp2a_iconset_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
