#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("KeyValueTest.Resource", IsApplication=true)]

namespace KeyValueTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int bottom_bar = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int entry_contents = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int entry_divider2 = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int entry_edit = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int entry_scroll = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int extra_strings = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int title = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int top = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int value = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int entry_section = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
