#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("keepass2android.Resource", IsApplication=true)]

namespace keepass2android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::KeePassLib2Android.Resource.String.library_name = global::keepass2android.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int anim_enter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int anim_enter_back = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int anim_leave = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int anim_leave_back = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090007
			public const int AcceptAllServerCertificates_options = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int AcceptAllServerCertificates_values = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int clipboard_timeout_options = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int clipboard_timeout_values = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int cred_remember_modes = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int list_size_options = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int list_size_values = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int password_modes = 2131296262;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int help_text = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080007
			public const int CopyToClipboardNotification_default = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int OpenKp2aKeyboardAutomatically_default = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int PreloadDatabaseEnabled_default = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int RememberRecentFiles_default = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int ShowUnlockedNotification_default = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int ShowUsernameInList_default = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int TanExpiresOnUse_default = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int UseKp2aKeyboard_default = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int keyfile_default = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int maskpass_default = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int omitbackup_default = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int sort_default = 2131230722;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070007
			public const int bg_gray = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int blue_highlight = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int dark_gray = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int element_being_moved = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int emphasis = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int emphasis2 = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int group = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int group_header_button_pressed = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int icon_background = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int icon_text = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int light_gray = 2131165192;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int activity_horizontal_margin = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int activity_vertical_margin = 2131361793;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlueButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_new_group = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_new_group_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int collections_collection = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int collections_new_label = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int device_access_new_account = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int device_access_new_account_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int device_access_not_secure = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EntryFieldHeaderBackground = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int extra_string_header = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int GreenButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int HeaderButtonBackground = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic00 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic01 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic02 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic03 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic04 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic05 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic06 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic07 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic08 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic09 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic10 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic11 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic12 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic13 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic14 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic15 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic16 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic17 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic18 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic19 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic20 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic21 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic22 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic23 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic24 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic25 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic26 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic27 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic28 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic29 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic30 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic31 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic32 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic33 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic34 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic35 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic36 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic37 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic38 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic39 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic40 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic41 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic42 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic43 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic44 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic45 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic46 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic47 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic48 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic49 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic50 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic51 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic52 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic53 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic54 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic55 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic56 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic57 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic58 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic59 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic60 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic61 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic62 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic63 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic64 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic65 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic66 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic67 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic68 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic99_blank = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_action_eye_open = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_action_search = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_keepass2android = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ic_keepass2android_nonet = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ic_launcher = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ic_launcher_folder_small = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ic_launcher_gray = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ic_launcher_offline = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ic_launcher_red = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ic_menu_add_field_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ic_menu_remove_field_holo_light = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ic_menu_view = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ic_storage_androidget = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ic_storage_androidsend = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ic_storage_dropbox = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ic_storage_dropboxKP2A = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ic_storage_file = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_storage_ftp = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_storage_gdrive = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_storage_http = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_storage_https = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_storage_sftp = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_storage_skydrive = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_unlocked_gray = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int location_web_site = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int navigation_accept = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int navigation_accept_dark = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int navigation_cancel = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int navigation_previous_item = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int navigation_previous_item_dark = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int notify = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int notify_keyboard = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int oktoberfest = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int RedButton = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int section_header = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int transparent = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int YellowButton = 2130837622;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0011
			public const int Credit = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public const int Credit2 = 2131558418;
			
			// aapt resource value: 0x7f0d0089
			public const int IconGridView = 2131558537;
			
			// aapt resource value: 0x7f0d00a8
			public const int QuickUnlock_button = 2131558568;
			
			// aapt resource value: 0x7f0d00a9
			public const int QuickUnlock_buttonLock = 2131558569;
			
			// aapt resource value: 0x7f0d00a6
			public const int QuickUnlock_label = 2131558566;
			
			// aapt resource value: 0x7f0d00a7
			public const int QuickUnlock_password = 2131558567;
			
			// aapt resource value: 0x7f0d006a
			public const int RelativeLayout = 2131558506;
			
			// aapt resource value: 0x7f0d0069
			public const int ScrollView = 2131558505;
			
			// aapt resource value: 0x7f0d0000
			public const int about_title = 2131558400;
			
			// aapt resource value: 0x7f0d0067
			public const int accept_button = 2131558503;
			
			// aapt resource value: 0x7f0d003a
			public const int add_advanced = 2131558458;
			
			// aapt resource value: 0x7f0d007d
			public const int add_entry = 2131558525;
			
			// aapt resource value: 0x7f0d007c
			public const int add_group = 2131558524;
			
			// aapt resource value: 0x7f0d00bc
			public const int add_url_entry = 2131558588;
			
			// aapt resource value: 0x7f0d0039
			public const int advanced_container = 2131558457;
			
			// aapt resource value: 0x7f0d000f
			public const int android_filechooser_contrib = 2131558415;
			
			// aapt resource value: 0x7f0d000c
			public const int author = 2131558412;
			
			// aapt resource value: 0x7f0d003c
			public const int binaries = 2131558460;
			
			// aapt resource value: 0x7f0d0049
			public const int bottom_bar = 2131558473;
			
			// aapt resource value: 0x7f0d0061
			public const int bottom_layout = 2131558497;
			
			// aapt resource value: 0x7f0d005c
			public const int browse_button = 2131558492;
			
			// aapt resource value: 0x7f0d0016
			public const int btn_change_location = 2131558422;
			
			// aapt resource value: 0x7f0d001f
			public const int btn_create = 2131558431;
			
			// aapt resource value: 0x7f0d006f
			public const int btn_length12 = 2131558511;
			
			// aapt resource value: 0x7f0d006e
			public const int btn_length16 = 2131558510;
			
			// aapt resource value: 0x7f0d0071
			public const int btn_length6 = 2131558513;
			
			// aapt resource value: 0x7f0d0070
			public const int btn_length8 = 2131558512;
			
			// aapt resource value: 0x7f0d0082
			public const int cancel = 2131558530;
			
			// aapt resource value: 0x7f0d0068
			public const int cancel_button = 2131558504;
			
			// aapt resource value: 0x7f0d007f
			public const int cancel_insert_element = 2131558527;
			
			// aapt resource value: 0x7f0d00b9
			public const int cbCaseSensitive = 2131558585;
			
			// aapt resource value: 0x7f0d00ba
			public const int cbExcludeExpiredEntries = 2131558586;
			
			// aapt resource value: 0x7f0d00af
			public const int cbRegEx = 2131558575;
			
			// aapt resource value: 0x7f0d00b8
			public const int cbSearchInGroupName = 2131558584;
			
			// aapt resource value: 0x7f0d00b5
			public const int cbSearchInNotes = 2131558581;
			
			// aapt resource value: 0x7f0d00b6
			public const int cbSearchInOtherStrings = 2131558582;
			
			// aapt resource value: 0x7f0d00b4
			public const int cbSearchInPassword = 2131558580;
			
			// aapt resource value: 0x7f0d00b7
			public const int cbSearchInTags = 2131558583;
			
			// aapt resource value: 0x7f0d00b1
			public const int cbSearchInTitle = 2131558577;
			
			// aapt resource value: 0x7f0d00b2
			public const int cbSearchInUrl = 2131558578;
			
			// aapt resource value: 0x7f0d00b3
			public const int cbSearchInUsername = 2131558579;
			
			// aapt resource value: 0x7f0d007a
			public const int cb_brackets = 2131558522;
			
			// aapt resource value: 0x7f0d0075
			public const int cb_digits = 2131558517;
			
			// aapt resource value: 0x7f0d0074
			public const int cb_lowercase = 2131558516;
			
			// aapt resource value: 0x7f0d0076
			public const int cb_minus = 2131558518;
			
			// aapt resource value: 0x7f0d0078
			public const int cb_space = 2131558520;
			
			// aapt resource value: 0x7f0d0079
			public const int cb_specials = 2131558521;
			
			// aapt resource value: 0x7f0d0077
			public const int cb_underline = 2131558519;
			
			// aapt resource value: 0x7f0d0073
			public const int cb_uppercase = 2131558515;
			
			// aapt resource value: 0x7f0d000b
			public const int contributors_title = 2131558411;
			
			// aapt resource value: 0x7f0d005f
			public const int create = 2131558495;
			
			// aapt resource value: 0x7f0d00cb
			public const int cred_password = 2131558603;
			
			// aapt resource value: 0x7f0d00cc
			public const int cred_remember_mode = 2131558604;
			
			// aapt resource value: 0x7f0d00ca
			public const int cred_username = 2131558602;
			
			// aapt resource value: 0x7f0d0029
			public const int delete_extra = 2131558441;
			
			// aapt resource value: 0x7f0d000a
			public const int disclaimer = 2131558410;
			
			// aapt resource value: 0x7f0d0009
			public const int disclaimer_title = 2131558409;
			
			// aapt resource value: 0x7f0d0001
			public const int divider1 = 2131558401;
			
			// aapt resource value: 0x7f0d0005
			public const int divider2 = 2131558405;
			
			// aapt resource value: 0x7f0d0008
			public const int divider3 = 2131558408;
			
			// aapt resource value: 0x7f0d0022
			public const int donate_question = 2131558434;
			
			// aapt resource value: 0x7f0d0044
			public const int edit_extra = 2131558468;
			
			// aapt resource value: 0x7f0d00a4
			public const int enable_quickunlock = 2131558564;
			
			// aapt resource value: 0x7f0d003b
			public const int entry_binaries_label = 2131558459;
			
			// aapt resource value: 0x7f0d0037
			public const int entry_comment = 2131558455;
			
			// aapt resource value: 0x7f0d0036
			public const int entry_comment_label = 2131558454;
			
			// aapt resource value: 0x7f0d001b
			public const int entry_confpassword = 2131558427;
			
			// aapt resource value: 0x7f0d0035
			public const int entry_confpassword_label = 2131558453;
			
			// aapt resource value: 0x7f0d004c
			public const int entry_contents = 2131558476;
			
			// aapt resource value: 0x7f0d0051
			public const int entry_created = 2131558481;
			
			// aapt resource value: 0x7f0d0050
			public const int entry_created_label = 2131558480;
			
			// aapt resource value: 0x7f0d004b
			public const int entry_divider2 = 2131558475;
			
			// aapt resource value: 0x7f0d004a
			public const int entry_edit = 2131558474;
			
			// aapt resource value: 0x7f0d0043
			public const int entry_expires = 2131558467;
			
			// aapt resource value: 0x7f0d0042
			public const int entry_expires_checkbox = 2131558466;
			
			// aapt resource value: 0x7f0d0041
			public const int entry_expires_label = 2131558465;
			
			// aapt resource value: 0x7f0d0038
			public const int entry_extra_strings_label = 2131558456;
			
			// aapt resource value: 0x7f0d0045
			public const int entry_icon = 2131558469;
			
			// aapt resource value: 0x7f0d0053
			public const int entry_modified = 2131558483;
			
			// aapt resource value: 0x7f0d0052
			public const int entry_modified_label = 2131558482;
			
			// aapt resource value: 0x7f0d0040
			public const int entry_override_url = 2131558464;
			
			// aapt resource value: 0x7f0d003f
			public const int entry_override_url_label = 2131558463;
			
			// aapt resource value: 0x7f0d001a
			public const int entry_password = 2131558426;
			
			// aapt resource value: 0x7f0d0034
			public const int entry_password_label = 2131558452;
			
			// aapt resource value: 0x7f0d002b
			public const int entry_save = 2131558443;
			
			// aapt resource value: 0x7f0d002a
			public const int entry_save_header = 2131558442;
			
			// aapt resource value: 0x7f0d002c
			public const int entry_scroll = 2131558444;
			
			// aapt resource value: 0x7f0d004e
			public const int entry_table = 2131558478;
			
			// aapt resource value: 0x7f0d003e
			public const int entry_tags = 2131558462;
			
			// aapt resource value: 0x7f0d003d
			public const int entry_tags_label = 2131558461;
			
			// aapt resource value: 0x7f0d0046
			public const int entry_text = 2131558470;
			
			// aapt resource value: 0x7f0d0047
			public const int entry_text_detail = 2131558471;
			
			// aapt resource value: 0x7f0d002f
			public const int entry_title = 2131558447;
			
			// aapt resource value: 0x7f0d002d
			public const int entry_title_label = 2131558445;
			
			// aapt resource value: 0x7f0d0033
			public const int entry_url = 2131558451;
			
			// aapt resource value: 0x7f0d0032
			public const int entry_url_label = 2131558450;
			
			// aapt resource value: 0x7f0d0031
			public const int entry_user_name = 2131558449;
			
			// aapt resource value: 0x7f0d0030
			public const int entry_user_name_label = 2131558448;
			
			// aapt resource value: 0x7f0d004f
			public const int extra_strings = 2131558479;
			
			// aapt resource value: 0x7f0d0007
			public const int feedback = 2131558407;
			
			// aapt resource value: 0x7f0d0006
			public const int feedback_title = 2131558406;
			
			// aapt resource value: 0x7f0d0054
			public const int file_filename = 2131558484;
			
			// aapt resource value: 0x7f0d0055
			public const int file_listtop = 2131558485;
			
			// aapt resource value: 0x7f0d0064
			public const int file_select = 2131558500;
			
			// aapt resource value: 0x7f0d008d
			public const int filename = 2131558541;
			
			// aapt resource value: 0x7f0d005a
			public const int filename_form = 2131558490;
			
			// aapt resource value: 0x7f0d008a
			public const int filename_group = 2131558538;
			
			// aapt resource value: 0x7f0d008b
			public const int filename_label = 2131558539;
			
			// aapt resource value: 0x7f0d008c
			public const int filenamescroll = 2131558540;
			
			// aapt resource value: 0x7f0d0014
			public const int filestorage_label = 2131558420;
			
			// aapt resource value: 0x7f0d0013
			public const int filestorage_logo = 2131558419;
			
			// aapt resource value: 0x7f0d0060
			public const int fnv_cancel = 2131558496;
			
			// aapt resource value: 0x7f0d0065
			public const int fssa_progress_bar = 2131558501;
			
			// aapt resource value: 0x7f0d000d
			public const int further_authors = 2131558413;
			
			// aapt resource value: 0x7f0d0018
			public const int generate_button = 2131558424;
			
			// aapt resource value: 0x7f0d006c
			public const int generate_password_button = 2131558508;
			
			// aapt resource value: 0x7f0d007b
			public const int group_header = 2131558523;
			
			// aapt resource value: 0x7f0d0084
			public const int group_icon = 2131558532;
			
			// aapt resource value: 0x7f0d0086
			public const int group_label = 2131558534;
			
			// aapt resource value: 0x7f0d0080
			public const int group_name = 2131558528;
			
			// aapt resource value: 0x7f0d0085
			public const int group_text = 2131558533;
			
			// aapt resource value: 0x7f0d00c8
			public const int help = 2131558600;
			
			// aapt resource value: 0x7f0d0083
			public const int icon = 2131558531;
			
			// aapt resource value: 0x7f0d002e
			public const int icon_button = 2131558446;
			
			// aapt resource value: 0x7f0d0087
			public const int icon_image = 2131558535;
			
			// aapt resource value: 0x7f0d0088
			public const int icon_text = 2131558536;
			
			// aapt resource value: 0x7f0d0062
			public const int imglogo = 2131558498;
			
			// aapt resource value: 0x7f0d0023
			public const int imgoktfest = 2131558435;
			
			// aapt resource value: 0x7f0d0095
			public const int init_otp = 2131558549;
			
			// aapt resource value: 0x7f0d00c5
			public const int initial_dir = 2131558597;
			
			// aapt resource value: 0x7f0d007e
			public const int insert_element = 2131558526;
			
			// aapt resource value: 0x7f0d0010
			public const int keyboard_contrib = 2131558416;
			
			// aapt resource value: 0x7f0d0091
			public const int keyfileLine = 2131558545;
			
			// aapt resource value: 0x7f0d001e
			public const int keyfile_filename = 2131558430;
			
			// aapt resource value: 0x7f0d001c
			public const int keyfile_title = 2131558428;
			
			// aapt resource value: 0x7f0d00a3
			public const int kill_app = 2131558563;
			
			// aapt resource value: 0x7f0d0063
			public const int label_app_name = 2131558499;
			
			// aapt resource value: 0x7f0d0015
			public const int label_filename = 2131558421;
			
			// aapt resource value: 0x7f0d005b
			public const int label_open_by_filename = 2131558491;
			
			// aapt resource value: 0x7f0d005d
			public const int label_open_by_filename_details = 2131558493;
			
			// aapt resource value: 0x7f0d0056
			public const int label_warning = 2131558486;
			
			// aapt resource value: 0x7f0d0072
			public const int length = 2131558514;
			
			// aapt resource value: 0x7f0d006d
			public const int length_label = 2131558509;
			
			// aapt resource value: 0x7f0d00ae
			public const int linearLayout1 = 2131558574;
			
			// aapt resource value: 0x7f0d00d6
			public const int menu_about = 2131558614;
			
			// aapt resource value: 0x7f0d00d5
			public const int menu_app_settings = 2131558613;
			
			// aapt resource value: 0x7f0d00d4
			public const int menu_cancel_edit = 2131558612;
			
			// aapt resource value: 0x7f0d00dc
			public const int menu_change_db = 2131558620;
			
			// aapt resource value: 0x7f0d00d8
			public const int menu_change_master_key = 2131558616;
			
			// aapt resource value: 0x7f0d00cd
			public const int menu_donate = 2131558605;
			
			// aapt resource value: 0x7f0d00cf
			public const int menu_goto_url = 2131558607;
			
			// aapt resource value: 0x7f0d00d0
			public const int menu_lock = 2131558608;
			
			// aapt resource value: 0x7f0d00d2
			public const int menu_rate = 2131558610;
			
			// aapt resource value: 0x7f0d00d7
			public const int menu_search = 2131558615;
			
			// aapt resource value: 0x7f0d00db
			public const int menu_search_advanced = 2131558619;
			
			// aapt resource value: 0x7f0d00da
			public const int menu_sort = 2131558618;
			
			// aapt resource value: 0x7f0d00d1
			public const int menu_suggest_improvements = 2131558609;
			
			// aapt resource value: 0x7f0d00d9
			public const int menu_sync = 2131558617;
			
			// aapt resource value: 0x7f0d00ce
			public const int menu_toggle_pass = 2131558606;
			
			// aapt resource value: 0x7f0d00d3
			public const int menu_translate = 2131558611;
			
			// aapt resource value: 0x7f0d0025
			public const int no_donate = 2131558437;
			
			// aapt resource value: 0x7f0d00bd
			public const int no_results = 2131558589;
			
			// aapt resource value: 0x7f0d0081
			public const int ok = 2131558529;
			
			// aapt resource value: 0x7f0d0024
			public const int ok_donate = 2131558436;
			
			// aapt resource value: 0x7f0d005e
			public const int open = 2131558494;
			
			// aapt resource value: 0x7f0d0099
			public const int otp1 = 2131558553;
			
			// aapt resource value: 0x7f0d009a
			public const int otp2 = 2131558554;
			
			// aapt resource value: 0x7f0d009b
			public const int otp3 = 2131558555;
			
			// aapt resource value: 0x7f0d009c
			public const int otp4 = 2131558556;
			
			// aapt resource value: 0x7f0d009d
			public const int otp5 = 2131558557;
			
			// aapt resource value: 0x7f0d009e
			public const int otp6 = 2131558558;
			
			// aapt resource value: 0x7f0d0097
			public const int otpEntry = 2131558551;
			
			// aapt resource value: 0x7f0d0094
			public const int otpInitView = 2131558548;
			
			// aapt resource value: 0x7f0d009f
			public const int otpSecretLine = 2131558559;
			
			// aapt resource value: 0x7f0d0093
			public const int otpView = 2131558547;
			
			// aapt resource value: 0x7f0d0098
			public const int otp_expl = 2131558552;
			
			// aapt resource value: 0x7f0d0096
			public const int otps_pending = 2131558550;
			
			// aapt resource value: 0x7f0d00a1
			public const int otpsecret_format_spinner = 2131558561;
			
			// aapt resource value: 0x7f0d00bf
			public const int pass_conf_password = 2131558591;
			
			// aapt resource value: 0x7f0d0092
			public const int pass_keyfile = 2131558546;
			
			// aapt resource value: 0x7f0d00a2
			public const int pass_ok = 2131558562;
			
			// aapt resource value: 0x7f0d00a0
			public const int pass_otpsecret = 2131558560;
			
			// aapt resource value: 0x7f0d00be
			public const int pass_password = 2131558590;
			
			// aapt resource value: 0x7f0d006b
			public const int password = 2131558507;
			
			// aapt resource value: 0x7f0d0090
			public const int passwordLine = 2131558544;
			
			// aapt resource value: 0x7f0d008e
			public const int password_label = 2131558542;
			
			// aapt resource value: 0x7f0d008f
			public const int password_mode_spinner = 2131558543;
			
			// aapt resource value: 0x7f0d0017
			public const int password_title = 2131558423;
			
			// aapt resource value: 0x7f0d000e
			public const int plugin1 = 2131558414;
			
			// aapt resource value: 0x7f0d00c1
			public const int portsep = 2131558593;
			
			// aapt resource value: 0x7f0d0028
			public const int protection = 2131558440;
			
			// aapt resource value: 0x7f0d00a5
			public const int qu_filename = 2131558565;
			
			// aapt resource value: 0x7f0d0020
			public const int rounds = 2131558432;
			
			// aapt resource value: 0x7f0d0021
			public const int rounds_explaination = 2131558433;
			
			// aapt resource value: 0x7f0d00ad
			public const int scrollView1 = 2131558573;
			
			// aapt resource value: 0x7f0d00ac
			public const int searchEditText = 2131558572;
			
			// aapt resource value: 0x7f0d00ab
			public const int search_button = 2131558571;
			
			// aapt resource value: 0x7f0d00b0
			public const int search_in_label = 2131558576;
			
			// aapt resource value: 0x7f0d00aa
			public const int search_label = 2131558570;
			
			// aapt resource value: 0x7f0d00bb
			public const int select_other_entry = 2131558587;
			
			// aapt resource value: 0x7f0d00c0
			public const int sftp_host = 2131558592;
			
			// aapt resource value: 0x7f0d00c6
			public const int sftp_initial_dir = 2131558598;
			
			// aapt resource value: 0x7f0d00c4
			public const int sftp_password = 2131558596;
			
			// aapt resource value: 0x7f0d00c2
			public const int sftp_port = 2131558594;
			
			// aapt resource value: 0x7f0d00c3
			public const int sftp_user = 2131558595;
			
			// aapt resource value: 0x7f0d0059
			public const int start_create = 2131558489;
			
			// aapt resource value: 0x7f0d00c7
			public const int start_create_import = 2131558599;
			
			// aapt resource value: 0x7f0d0057
			public const int start_open_file = 2131558487;
			
			// aapt resource value: 0x7f0d0058
			public const int start_open_url = 2131558488;
			
			// aapt resource value: 0x7f0d00c9
			public const int text = 2131558601;
			
			// aapt resource value: 0x7f0d0066
			public const int textView = 2131558502;
			
			// aapt resource value: 0x7f0d0026
			public const int title = 2131558438;
			
			// aapt resource value: 0x7f0d0048
			public const int title_block = 2131558472;
			
			// aapt resource value: 0x7f0d0019
			public const int toggle_password = 2131558425;
			
			// aapt resource value: 0x7f0d004d
			public const int top = 2131558477;
			
			// aapt resource value: 0x7f0d001d
			public const int use_keyfile = 2131558429;
			
			// aapt resource value: 0x7f0d0027
			public const int value = 2131558439;
			
			// aapt resource value: 0x7f0d0004
			public const int versionB = 2131558404;
			
			// aapt resource value: 0x7f0d0003
			public const int versionX = 2131558403;
			
			// aapt resource value: 0x7f0d0002
			public const int version_title = 2131558402;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int create_database = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int database_settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int donate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int edit_extra_string_dialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int entry_edit = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int entry_edit_section = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int entry_extrastring_title = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int entry_extrastring_value = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int entry_list_entry = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int entry_section = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int entry_view = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int entry_view_contents = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int entry_view_test = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int file_row = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int file_selection = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int file_selection_buttons = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int file_selection_filename = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int file_selection_no_recent = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int file_storage_setup = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int filestorage_selection = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int filestorage_selection_listitem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int filestorage_selection_listitem_kp2a = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int generate_password = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int group_add_entry = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int group_edit = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int group_empty = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int group_header = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int group_list_entry = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int icon = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int icon_picker = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int InViewButton = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int password = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int QuickUnlock = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int QuickUnlock_Unused = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int SaveButton = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int search = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int searchurlresults = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int searchurlresults_empty = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int set_password = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int sftpcredentials = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int StartScreenButtons = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int text_with_help = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int url_credentials = 2130903083;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int entry = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int entry_edit = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int fileselect = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int group = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public const int password = 2131492868;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06003b
			public const int AboutText = 2131099707;
			
			// aapt resource value: 0x7f060036
			public const int AcceptAllServerCertificates_default = 2131099702;
			
			// aapt resource value: 0x7f06002c
			public const int AcceptAllServerCertificates_key = 2131099692;
			
			// aapt resource value: 0x7f060129
			public const int AcceptAllServerCertificates_summary = 2131099945;
			
			// aapt resource value: 0x7f060128
			public const int AcceptAllServerCertificates_title = 2131099944;
			
			// aapt resource value: 0x7f060116
			public const int AddUrlToEntryDialog_text = 2131099926;
			
			// aapt resource value: 0x7f060115
			public const int AddUrlToEntryDialog_title = 2131099925;
			
			// aapt resource value: 0x7f060148
			public const int AddingEntry = 2131099976;
			
			// aapt resource value: 0x7f060149
			public const int AddingGroup = 2131099977;
			
			// aapt resource value: 0x7f06013e
			public const int AskDeletePermanentlyEntry = 2131099966;
			
			// aapt resource value: 0x7f06013f
			public const int AskDeletePermanentlyGroup = 2131099967;
			
			// aapt resource value: 0x7f060140
			public const int AskDeletePermanently_title = 2131099968;
			
			// aapt resource value: 0x7f060143
			public const int AskDiscardChanges = 2131099971;
			
			// aapt resource value: 0x7f060144
			public const int AskDiscardChanges_title = 2131099972;
			
			// aapt resource value: 0x7f060138
			public const int AskOverwriteBinary = 2131099960;
			
			// aapt resource value: 0x7f06013b
			public const int AskOverwriteBinary_no = 2131099963;
			
			// aapt resource value: 0x7f060139
			public const int AskOverwriteBinary_title = 2131099961;
			
			// aapt resource value: 0x7f06013a
			public const int AskOverwriteBinary_yes = 2131099962;
			
			// aapt resource value: 0x7f060142
			public const int AskReloadFile = 2131099970;
			
			// aapt resource value: 0x7f060141
			public const int AskReloadFile_title = 2131099969;
			
			// aapt resource value: 0x7f06013c
			public const int AttachFailed = 2131099964;
			
			// aapt resource value: 0x7f06001d
			public const int BinaryDirectory_default = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int BinaryDirectory_key = 2131099676;
			
			// aapt resource value: 0x7f06010e
			public const int BinaryDirectory_summary = 2131099918;
			
			// aapt resource value: 0x7f06010d
			public const int BinaryDirectory_title = 2131099917;
			
			// aapt resource value: 0x7f06016c
			public const int CannotMoveGroupHere = 2131100012;
			
			// aapt resource value: 0x7f06019f
			public const int CertificateFailure = 2131100063;
			
			// aapt resource value: 0x7f06019e
			public const int CertificateWarning = 2131100062;
			
			// aapt resource value: 0x7f0601ae
			public const int ChangeLog = 2131100078;
			
			// aapt resource value: 0x7f0601ad
			public const int ChangeLog_0_7 = 2131100077;
			
			// aapt resource value: 0x7f0601ab
			public const int ChangeLog_0_8 = 2131100075;
			
			// aapt resource value: 0x7f0601aa
			public const int ChangeLog_0_8_1 = 2131100074;
			
			// aapt resource value: 0x7f0601a9
			public const int ChangeLog_0_8_2 = 2131100073;
			
			// aapt resource value: 0x7f0601a8
			public const int ChangeLog_0_8_3 = 2131100072;
			
			// aapt resource value: 0x7f0601a7
			public const int ChangeLog_0_8_4 = 2131100071;
			
			// aapt resource value: 0x7f0601a6
			public const int ChangeLog_0_8_5 = 2131100070;
			
			// aapt resource value: 0x7f0601a5
			public const int ChangeLog_0_8_6 = 2131100069;
			
			// aapt resource value: 0x7f0601a4
			public const int ChangeLog_0_9 = 2131100068;
			
			// aapt resource value: 0x7f0601a3
			public const int ChangeLog_0_9_1 = 2131100067;
			
			// aapt resource value: 0x7f0601a2
			public const int ChangeLog_0_9_2 = 2131100066;
			
			// aapt resource value: 0x7f0601a1
			public const int ChangeLog_0_9_3 = 2131100065;
			
			// aapt resource value: 0x7f0601ac
			public const int ChangeLog_keptDonate = 2131100076;
			
			// aapt resource value: 0x7f0601a0
			public const int ChangeLog_title = 2131100064;
			
			// aapt resource value: 0x7f06002d
			public const int CheckForFileChangesOnSave_key = 2131099693;
			
			// aapt resource value: 0x7f06012d
			public const int CheckForFileChangesOnSave_summary = 2131099949;
			
			// aapt resource value: 0x7f06012c
			public const int CheckForFileChangesOnSave_title = 2131099948;
			
			// aapt resource value: 0x7f06015d
			public const int CheckingDatabaseForChanges = 2131099997;
			
			// aapt resource value: 0x7f060151
			public const int CheckingTargetFileForChanges = 2131099985;
			
			// aapt resource value: 0x7f060058
			public const int ClearClipboard = 2131099736;
			
			// aapt resource value: 0x7f06012b
			public const int ClearOfflineCache_question = 2131099947;
			
			// aapt resource value: 0x7f06012a
			public const int ClearOfflineCache_title = 2131099946;
			
			// aapt resource value: 0x7f060031
			public const int CopyToClipboardNotification_key = 2131099697;
			
			// aapt resource value: 0x7f06015f
			public const int CouldNotLoadFromRemote = 2131099999;
			
			// aapt resource value: 0x7f06015e
			public const int CouldNotSaveToRemote = 2131099998;
			
			// aapt resource value: 0x7f060191
			public const int CouldntLoadOtpAuxFile = 2131100049;
			
			// aapt resource value: 0x7f060192
			public const int CouldntLoadOtpAuxFile_Hint = 2131100050;
			
			// aapt resource value: 0x7f060198
			public const int CouldntParseOtpSecret = 2131100056;
			
			// aapt resource value: 0x7f06003c
			public const int CreditsText = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int CreditsTextSFTP = 2131099709;
			
			// aapt resource value: 0x7f06014f
			public const int DecodingDatabase = 2131099983;
			
			// aapt resource value: 0x7f06014a
			public const int DeletingEntry = 2131099978;
			
			// aapt resource value: 0x7f06014b
			public const int DeletingGroup = 2131099979;
			
			// aapt resource value: 0x7f060158
			public const int DownloadingRemoteFile = 2131099992;
			
			// aapt resource value: 0x7f06016a
			public const int ErrorOcurred = 2131100010;
			
			// aapt resource value: 0x7f06019a
			public const int ErrorUpdatingOtpAuxFile = 2131100058;
			
			// aapt resource value: 0x7f060055
			public const int FileHandling_prefs = 2131099733;
			
			// aapt resource value: 0x7f060022
			public const int FileHandling_prefs_key = 2131099682;
			
			// aapt resource value: 0x7f06008a
			public const int FileNotFound = 2131099786;
			
			// aapt resource value: 0x7f06015b
			public const int FilesInSync = 2131099995;
			
			// aapt resource value: 0x7f06009b
			public const int InvalidPassword = 2131099803;
			
			// aapt resource value: 0x7f060028
			public const int LastInfoVersionCode_key = 2131099688;
			
			// aapt resource value: 0x7f060162
			public const int LoadedFromRemoteInSync = 2131100002;
			
			// aapt resource value: 0x7f06002a
			public const int LockWhenScreenOff_key = 2131099690;
			
			// aapt resource value: 0x7f060125
			public const int LockWhenScreenOff_summary = 2131099941;
			
			// aapt resource value: 0x7f060124
			public const int LockWhenScreenOff_title = 2131099940;
			
			// aapt resource value: 0x7f06002e
			public const int MarketURL = 2131099694;
			
			// aapt resource value: 0x7f0600a5
			public const int MaskedPassword = 2131099813;
			
			// aapt resource value: 0x7f060153
			public const int MessageSyncQuestion = 2131099987;
			
			// aapt resource value: 0x7f060156
			public const int NoOverwrite = 2131099990;
			
			// aapt resource value: 0x7f060161
			public const int NotifyOpenFromLocalDueToConflict = 2131100001;
			
			// aapt resource value: 0x7f060033
			public const int OpenKp2aKeyboardAutomatically_key = 2131099699;
			
			// aapt resource value: 0x7f060133
			public const int OpenKp2aKeyboardAutomatically_summary = 2131099955;
			
			// aapt resource value: 0x7f060132
			public const int OpenKp2aKeyboardAutomatically_title = 2131099954;
			
			// aapt resource value: 0x7f060199
			public const int OtpKeyError = 2131100057;
			
			// aapt resource value: 0x7f060150
			public const int ParsingDatabase = 2131099984;
			
			// aapt resource value: 0x7f060038
			public const int PreloadDatabaseEnabled_key = 2131099704;
			
			// aapt resource value: 0x7f060137
			public const int PreloadDatabaseEnabled_summary = 2131099959;
			
			// aapt resource value: 0x7f060136
			public const int PreloadDatabaseEnabled_title = 2131099958;
			
			// aapt resource value: 0x7f060023
			public const int QuickUnlockDefaultEnabled_key = 2131099683;
			
			// aapt resource value: 0x7f060107
			public const int QuickUnlockDefaultEnabled_summary = 2131099911;
			
			// aapt resource value: 0x7f060106
			public const int QuickUnlockDefaultEnabled_title = 2131099910;
			
			// aapt resource value: 0x7f060026
			public const int QuickUnlockIconHidden_key = 2131099686;
			
			// aapt resource value: 0x7f060109
			public const int QuickUnlockIconHidden_summary = 2131099913;
			
			// aapt resource value: 0x7f060108
			public const int QuickUnlockIconHidden_title = 2131099912;
			
			// aapt resource value: 0x7f060025
			public const int QuickUnlockLength_default = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int QuickUnlockLength_key = 2131099684;
			
			// aapt resource value: 0x7f06010b
			public const int QuickUnlockLength_summary = 2131099915;
			
			// aapt resource value: 0x7f06010a
			public const int QuickUnlockLength_title = 2131099914;
			
			// aapt resource value: 0x7f060104
			public const int QuickUnlock_button = 2131099908;
			
			// aapt resource value: 0x7f06010c
			public const int QuickUnlock_fail = 2131099916;
			
			// aapt resource value: 0x7f060103
			public const int QuickUnlock_label = 2131099907;
			
			// aapt resource value: 0x7f060105
			public const int QuickUnlock_lockButton = 2131099909;
			
			// aapt resource value: 0x7f060054
			public const int QuickUnlock_prefs = 2131099732;
			
			// aapt resource value: 0x7f060021
			public const int QuickUnlock_prefs_key = 2131099681;
			
			// aapt resource value: 0x7f06013d
			public const int RecycleBin = 2131099965;
			
			// aapt resource value: 0x7f060019
			public const int RememberRecentFiles_key = 2131099673;
			
			// aapt resource value: 0x7f0600f7
			public const int RememberRecentFiles_summary = 2131099895;
			
			// aapt resource value: 0x7f0600f6
			public const int RememberRecentFiles_title = 2131099894;
			
			// aapt resource value: 0x7f060164
			public const int RemoteDatabaseUnchanged = 2131100004;
			
			// aapt resource value: 0x7f060166
			public const int ResolvedCacheConflictByUsingLocalOtpAux = 2131100006;
			
			// aapt resource value: 0x7f060165
			public const int ResolvedCacheConflictByUsingRemoteOtpAux = 2131100005;
			
			// aapt resource value: 0x7f06015a
			public const int RestoringRemoteFile = 2131099994;
			
			// aapt resource value: 0x7f060112
			public const int SaveAttachmentDialog_open = 2131099922;
			
			// aapt resource value: 0x7f060111
			public const int SaveAttachmentDialog_save = 2131099921;
			
			// aapt resource value: 0x7f060110
			public const int SaveAttachmentDialog_text = 2131099920;
			
			// aapt resource value: 0x7f06010f
			public const int SaveAttachmentDialog_title = 2131099919;
			
			// aapt resource value: 0x7f060114
			public const int SaveAttachment_Failed = 2131099924;
			
			// aapt resource value: 0x7f060113
			public const int SaveAttachment_doneMessage = 2131099923;
			
			// aapt resource value: 0x7f06019b
			public const int SavingOtpAuxFile = 2131100059;
			
			// aapt resource value: 0x7f06014c
			public const int SettingPassword = 2131099980;
			
			// aapt resource value: 0x7f06012f
			public const int ShowCopyToClipboardNotification_summary = 2131099951;
			
			// aapt resource value: 0x7f06012e
			public const int ShowCopyToClipboardNotification_title = 2131099950;
			
			// aapt resource value: 0x7f060131
			public const int ShowKp2aKeyboardNotification_summary = 2131099953;
			
			// aapt resource value: 0x7f060130
			public const int ShowKp2aKeyboardNotification_title = 2131099952;
			
			// aapt resource value: 0x7f060037
			public const int ShowUnlockedNotification_key = 2131099703;
			
			// aapt resource value: 0x7f060135
			public const int ShowUnlockedNotification_summary = 2131099957;
			
			// aapt resource value: 0x7f060134
			public const int ShowUnlockedNotification_title = 2131099956;
			
			// aapt resource value: 0x7f060018
			public const int ShowUsernameInList_key = 2131099672;
			
			// aapt resource value: 0x7f0600f5
			public const int ShowUsernameInList_summary = 2131099893;
			
			// aapt resource value: 0x7f0600f4
			public const int ShowUsernameInList_title = 2131099892;
			
			// aapt resource value: 0x7f06002f
			public const int SuggestionsURL = 2131099695;
			
			// aapt resource value: 0x7f06015c
			public const int SynchronizedDatabaseSuccessfully = 2131099996;
			
			// aapt resource value: 0x7f060157
			public const int SynchronizingCachedDatabase = 2131099991;
			
			// aapt resource value: 0x7f060154
			public const int SynchronizingDatabase = 2131099988;
			
			// aapt resource value: 0x7f060167
			public const int SynchronizingOtpAuxFile = 2131100007;
			
			// aapt resource value: 0x7f060017
			public const int TanExpiresOnUse_key = 2131099671;
			
			// aapt resource value: 0x7f0600f3
			public const int TanExpiresOnUse_summary = 2131099891;
			
			// aapt resource value: 0x7f0600f2
			public const int TanExpiresOnUse_title = 2131099890;
			
			// aapt resource value: 0x7f060152
			public const int TitleSyncQuestion = 2131099986;
			
			// aapt resource value: 0x7f06014e
			public const int TransformingKey = 2131099982;
			
			// aapt resource value: 0x7f060030
			public const int TranslationURL = 2131099696;
			
			// aapt resource value: 0x7f06014d
			public const int UndoingChanges = 2131099981;
			
			// aapt resource value: 0x7f060163
			public const int UpdatedCachedFileOnLoad = 2131100003;
			
			// aapt resource value: 0x7f060160
			public const int UpdatedRemoteFileOnLoad = 2131100000;
			
			// aapt resource value: 0x7f060159
			public const int UploadingFile = 2131099993;
			
			// aapt resource value: 0x7f060027
			public const int UsageCount_key = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int UseFileTransactions_key = 2131099689;
			
			// aapt resource value: 0x7f060123
			public const int UseFileTransactions_summary = 2131099939;
			
			// aapt resource value: 0x7f060122
			public const int UseFileTransactions_title = 2131099938;
			
			// aapt resource value: 0x7f060032
			public const int UseKp2aKeyboard_key = 2131099698;
			
			// aapt resource value: 0x7f06002b
			public const int UseOfflineCache_key = 2131099691;
			
			// aapt resource value: 0x7f060127
			public const int UseOfflineCache_summary = 2131099943;
			
			// aapt resource value: 0x7f060126
			public const int UseOfflineCache_title = 2131099942;
			
			// aapt resource value: 0x7f060155
			public const int YesSynchronize = 2131099989;
			
			// aapt resource value: 0x7f060039
			public const int about_feedback = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int about_homepage = 2131099706;
			
			// aapt resource value: 0x7f06003e
			public const int accept = 2131099710;
			
			// aapt resource value: 0x7f06011c
			public const int add_binary = 2131099932;
			
			// aapt resource value: 0x7f06003f
			public const int add_entry = 2131099711;
			
			// aapt resource value: 0x7f06011d
			public const int add_extra_string = 2131099933;
			
			// aapt resource value: 0x7f060041
			public const int add_group = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int add_group_title = 2131099714;
			
			// aapt resource value: 0x7f060040
			public const int add_url_entry = 2131099712;
			
			// aapt resource value: 0x7f060044
			public const int algorithm = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int algorithm_colon = 2131099717;
			
			// aapt resource value: 0x7f06000b
			public const int algorithm_key = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int app_key = 2131099660;
			
			// aapt resource value: 0x7f060046
			public const int app_name = 2131099718;
			
			// aapt resource value: 0x7f060048
			public const int app_name_nonet = 2131099720;
			
			// aapt resource value: 0x7f06004a
			public const int app_timeout = 2131099722;
			
			// aapt resource value: 0x7f06000d
			public const int app_timeout_key = 2131099661;
			
			// aapt resource value: 0x7f06004b
			public const int app_timeout_summary = 2131099723;
			
			// aapt resource value: 0x7f06004f
			public const int application = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int application_settings = 2131099728;
			
			// aapt resource value: 0x7f0600ea
			public const int author = 2131099882;
			
			// aapt resource value: 0x7f06005d
			public const int available_through_keyboard = 2131099741;
			
			// aapt resource value: 0x7f060056
			public const int brackets = 2131099734;
			
			// aapt resource value: 0x7f060185
			public const int button_change_location = 2131100037;
			
			// aapt resource value: 0x7f060057
			public const int cancel = 2131099735;
			
			// aapt resource value: 0x7f0600fb
			public const int caseSensitive = 2131099899;
			
			// aapt resource value: 0x7f060059
			public const int clipboard_timeout = 2131099737;
			
			// aapt resource value: 0x7f060034
			public const int clipboard_timeout_default = 2131099700;
			
			// aapt resource value: 0x7f06000f
			public const int clipboard_timeout_key = 2131099663;
			
			// aapt resource value: 0x7f06005a
			public const int clipboard_timeout_summary = 2131099738;
			
			// aapt resource value: 0x7f0600f0
			public const int contributors = 2131099888;
			
			// aapt resource value: 0x7f06005c
			public const int copy_password = 2131099740;
			
			// aapt resource value: 0x7f06005b
			public const int copy_username = 2131099739;
			
			// aapt resource value: 0x7f0600c9
			public const int create_database = 2131099849;
			
			// aapt resource value: 0x7f060060
			public const int creating_db_key = 2131099744;
			
			// aapt resource value: 0x7f060121
			public const int credentials_dialog_title = 2131099937;
			
			// aapt resource value: 0x7f0600ed
			public const int credit_android_filechooser = 2131099885;
			
			// aapt resource value: 0x7f0600ee
			public const int credit_keyboard = 2131099886;
			
			// aapt resource value: 0x7f0600ec
			public const int credit_plugin1 = 2131099884;
			
			// aapt resource value: 0x7f060061
			public const int current_group = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int current_group_root = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int database = 2131099747;
			
			// aapt resource value: 0x7f060168
			public const int database_file = 2131100008;
			
			// aapt resource value: 0x7f06011f
			public const int database_loaded_quickunlock_enabled = 2131099935;
			
			// aapt resource value: 0x7f060120
			public const int database_loaded_unlocked = 2131099936;
			
			// aapt resource value: 0x7f060182
			public const int database_location = 2131100034;
			
			// aapt resource value: 0x7f0600d3
			public const int database_name = 2131099859;
			
			// aapt resource value: 0x7f06001b
			public const int database_name_key = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int db_key = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int default_file_path = 2131099650;
			
			// aapt resource value: 0x7f0600d4
			public const int default_username = 2131099860;
			
			// aapt resource value: 0x7f06001a
			public const int default_username_key = 2131099674;
			
			// aapt resource value: 0x7f06011e
			public const int delete_extra_string = 2131099934;
			
			// aapt resource value: 0x7f060064
			public const int digits = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int disclaimer_formal = 2131099749;
			
			// aapt resource value: 0x7f060052
			public const int display_prefs = 2131099730;
			
			// aapt resource value: 0x7f060020
			public const int display_prefs_key = 2131099680;
			
			// aapt resource value: 0x7f06016d
			public const int donate_question = 2131100013;
			
			// aapt resource value: 0x7f060003
			public const int donate_url = 2131099651;
			
			// aapt resource value: 0x7f060043
			public const int edit_group_title = 2131099715;
			
			// aapt resource value: 0x7f060066
			public const int ellipsis = 2131099750;
			
			// aapt resource value: 0x7f060102
			public const int enable_quickunlock = 2131099906;
			
			// aapt resource value: 0x7f060067
			public const int enter_filename = 2131099751;
			
			// aapt resource value: 0x7f060101
			public const int enter_filename_details_create_import = 2131099905;
			
			// aapt resource value: 0x7f060100
			public const int enter_filename_details_url = 2131099904;
			
			// aapt resource value: 0x7f060173
			public const int enter_sftp_login_title = 2131100019;
			
			// aapt resource value: 0x7f060068
			public const int entry_accessed = 2131099752;
			
			// aapt resource value: 0x7f060078
			public const int entry_binaries = 2131099768;
			
			// aapt resource value: 0x7f060069
			public const int entry_cancel = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int entry_comment = 2131099754;
			
			// aapt resource value: 0x7f06006d
			public const int entry_confpassword = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int entry_created = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int entry_expires = 2131099759;
			
			// aapt resource value: 0x7f060077
			public const int entry_extra_strings = 2131099767;
			
			// aapt resource value: 0x7f060070
			public const int entry_keyfile = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int entry_modified = 2131099761;
			
			// aapt resource value: 0x7f06006c
			public const int entry_override_url = 2131099756;
			
			// aapt resource value: 0x7f060072
			public const int entry_password = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int entry_save = 2131099763;
			
			// aapt resource value: 0x7f06006b
			public const int entry_tags = 2131099755;
			
			// aapt resource value: 0x7f060074
			public const int entry_title = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int entry_url = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int entry_user_name = 2131099766;
			
			// aapt resource value: 0x7f06018d
			public const int error_adding_keyfile = 2131100045;
			
			// aapt resource value: 0x7f060079
			public const int error_can_not_handle_uri = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int error_could_not_create_group = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int error_could_not_create_parent = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int error_database_exists = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int error_database_settings = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int error_failed_to_launch_link = 2131099774;
			
			// aapt resource value: 0x7f060080
			public const int error_file_not_create = 2131099776;
			
			// aapt resource value: 0x7f06007f
			public const int error_filename_required = 2131099775;
			
			// aapt resource value: 0x7f060081
			public const int error_invalid_db = 2131099777;
			
			// aapt resource value: 0x7f060117
			public const int error_invalid_expiry_date = 2131099927;
			
			// aapt resource value: 0x7f060082
			public const int error_invalid_path = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int error_no_name = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int error_nopass = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int error_pass_gen_type = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int error_pass_match = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int error_rounds_not_number = 2131099783;
			
			// aapt resource value: 0x7f060118
			public const int error_string_key = 2131099928;
			
			// aapt resource value: 0x7f060088
			public const int error_title_required = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int error_wrong_length = 2131099785;
			
			// aapt resource value: 0x7f0600f9
			public const int excludeExpiredEntries = 2131099897;
			
			// aapt resource value: 0x7f060119
			public const int field_name = 2131099929;
			
			// aapt resource value: 0x7f06011a
			public const int field_value = 2131099930;
			
			// aapt resource value: 0x7f06008b
			public const int file_browser = 2131099787;
			
			// aapt resource value: 0x7f060181
			public const int filestorage_setup_title = 2131100033;
			
			// aapt resource value: 0x7f06017d
			public const int filestoragehelp_dropboxKP2A = 2131100029;
			
			// aapt resource value: 0x7f060176
			public const int filestoragename_androidget = 2131100022;
			
			// aapt resource value: 0x7f060177
			public const int filestoragename_androidsend = 2131100023;
			
			// aapt resource value: 0x7f06017b
			public const int filestoragename_dropbox = 2131100027;
			
			// aapt resource value: 0x7f06017c
			public const int filestoragename_dropboxKP2A = 2131100028;
			
			// aapt resource value: 0x7f060175
			public const int filestoragename_file = 2131100021;
			
			// aapt resource value: 0x7f060178
			public const int filestoragename_ftp = 2131100024;
			
			// aapt resource value: 0x7f06017e
			public const int filestoragename_gdrive = 2131100030;
			
			// aapt resource value: 0x7f060179
			public const int filestoragename_http = 2131100025;
			
			// aapt resource value: 0x7f06017a
			public const int filestoragename_https = 2131100026;
			
			// aapt resource value: 0x7f060180
			public const int filestoragename_sftp = 2131100032;
			
			// aapt resource value: 0x7f06017f
			public const int filestoragename_skydrive = 2131100031;
			
			// aapt resource value: 0x7f060006
			public const int further_author_names = 2131099654;
			
			// aapt resource value: 0x7f0600eb
			public const int further_authors = 2131099883;
			
			// aapt resource value: 0x7f06008c
			public const int generate_password = 2131099788;
			
			// aapt resource value: 0x7f06019d
			public const int get_regular_version = 2131100061;
			
			// aapt resource value: 0x7f06008d
			public const int group = 2131099789;
			
			// aapt resource value: 0x7f060183
			public const int help_database_location = 2131100035;
			
			// aapt resource value: 0x7f06018a
			public const int help_key_file = 2131100042;
			
			// aapt resource value: 0x7f060187
			public const int help_master_password = 2131100039;
			
			// aapt resource value: 0x7f06008e
			public const int hint_comment = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int hint_conf_pass = 2131099791;
			
			// aapt resource value: 0x7f060184
			public const int hint_database_location = 2131100036;
			
			// aapt resource value: 0x7f060090
			public const int hint_generated_password = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int hint_group_name = 2131099793;
			
			// aapt resource value: 0x7f06018b
			public const int hint_key_file = 2131100043;
			
			// aapt resource value: 0x7f060092
			public const int hint_keyfile = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int hint_length = 2131099795;
			
			// aapt resource value: 0x7f060095
			public const int hint_login_pass = 2131099797;
			
			// aapt resource value: 0x7f060188
			public const int hint_master_password = 2131100040;
			
			// aapt resource value: 0x7f060098
			public const int hint_override_url = 2131099800;
			
			// aapt resource value: 0x7f060094
			public const int hint_pass = 2131099796;
			
			// aapt resource value: 0x7f060170
			public const int hint_sftp_host = 2131100016;
			
			// aapt resource value: 0x7f060171
			public const int hint_sftp_port = 2131100017;
			
			// aapt resource value: 0x7f060099
			public const int hint_tags = 2131099801;
			
			// aapt resource value: 0x7f060096
			public const int hint_title = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int hint_url = 2131099799;
			
			// aapt resource value: 0x7f06009a
			public const int hint_username = 2131099802;
			
			// aapt resource value: 0x7f060004
			public const int homepage = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int homepage_short = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int icon_info = 2131099649;
			
			// aapt resource value: 0x7f06018e
			public const int init_otp = 2131100046;
			
			// aapt resource value: 0x7f060172
			public const int initial_directory = 2131100018;
			
			// aapt resource value: 0x7f0600e1
			public const int insert_element_here = 2131099873;
			
			// aapt resource value: 0x7f06009c
			public const int invalid_algorithm = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int invalid_db_sig = 2131099805;
			
			// aapt resource value: 0x7f060007
			public const int issues = 2131099655;
			
			// aapt resource value: 0x7f060189
			public const int key_file = 2131100041;
			
			// aapt resource value: 0x7f06009e
			public const int keyfile_does_not_exist = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int keyfile_is_empty = 2131099807;
			
			// aapt resource value: 0x7f060012
			public const int keyfile_key = 2131099666;
			
			// aapt resource value: 0x7f06004c
			public const int kill_app_label = 2131099724;
			
			// aapt resource value: 0x7f0600f8
			public const int kp2a_findUrl = 2131099896;
			
			// aapt resource value: 0x7f0600a0
			public const int length = 2131099808;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060035
			public const int list_size_default = 2131099701;
			
			// aapt resource value: 0x7f060015
			public const int list_size_key = 2131099669;
			
			// aapt resource value: 0x7f0600a2
			public const int list_size_summary = 2131099810;
			
			// aapt resource value: 0x7f0600a1
			public const int list_size_title = 2131099809;
			
			// aapt resource value: 0x7f06019c
			public const int loading = 2131100060;
			
			// aapt resource value: 0x7f0600a3
			public const int loading_database = 2131099811;
			
			// aapt resource value: 0x7f0600a4
			public const int lowercase = 2131099812;
			
			// aapt resource value: 0x7f060013
			public const int maskpass_key = 2131099667;
			
			// aapt resource value: 0x7f0600a7
			public const int maskpass_summary = 2131099815;
			
			// aapt resource value: 0x7f0600a6
			public const int maskpass_title = 2131099814;
			
			// aapt resource value: 0x7f0600c7
			public const int master_key_type = 2131099847;
			
			// aapt resource value: 0x7f060186
			public const int master_password = 2131100038;
			
			// aapt resource value: 0x7f0600a8
			public const int menu_about = 2131099816;
			
			// aapt resource value: 0x7f0600ad
			public const int menu_app_settings = 2131099821;
			
			// aapt resource value: 0x7f0600ba
			public const int menu_change_db = 2131099834;
			
			// aapt resource value: 0x7f0600a9
			public const int menu_change_key = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int menu_copy_pass = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int menu_copy_user = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int menu_create = 2131099820;
			
			// aapt resource value: 0x7f0600ae
			public const int menu_db_settings = 2131099822;
			
			// aapt resource value: 0x7f0600af
			public const int menu_delete = 2131099823;
			
			// aapt resource value: 0x7f0600b1
			public const int menu_donate = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int menu_edit = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int menu_hide_password = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int menu_lock = 2131099828;
			
			// aapt resource value: 0x7f0600b0
			public const int menu_move = 2131099824;
			
			// aapt resource value: 0x7f0600b5
			public const int menu_open = 2131099829;
			
			// aapt resource value: 0x7f0600b6
			public const int menu_rename = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int menu_search = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int menu_search_advanced = 2131099832;
			
			// aapt resource value: 0x7f0600b9
			public const int menu_url = 2131099833;
			
			// aapt resource value: 0x7f0600bb
			public const int minus = 2131099835;
			
			// aapt resource value: 0x7f0600bc
			public const int never = 2131099836;
			
			// aapt resource value: 0x7f0600be
			public const int no = 2131099838;
			
			// aapt resource value: 0x7f0600bf
			public const int no_keys = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int no_results = 2131099840;
			
			// aapt resource value: 0x7f06016f
			public const int no_thanks = 2131100015;
			
			// aapt resource value: 0x7f0600c1
			public const int no_url_handler = 2131099841;
			
			// aapt resource value: 0x7f06005e
			public const int not_possible_im_picker = 2131099742;
			
			// aapt resource value: 0x7f060008
			public const int oi_filemanager_market = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int oi_filemanager_web = 2131099657;
			
			// aapt resource value: 0x7f06016e
			public const int ok_donate = 2131100014;
			
			// aapt resource value: 0x7f060014
			public const int omitbackup_key = 2131099668;
			
			// aapt resource value: 0x7f0600c4
			public const int omitbackup_summary = 2131099844;
			
			// aapt resource value: 0x7f0600c3
			public const int omitbackup_title = 2131099843;
			
			// aapt resource value: 0x7f0600c2
			public const int open_recent = 2131099842;
			
			// aapt resource value: 0x7f060169
			public const int otp_aux_file = 2131100009;
			
			// aapt resource value: 0x7f060195
			public const int otp_discarded_because_db_open = 2131100053;
			
			// aapt resource value: 0x7f060193
			public const int otp_discarded_because_no_db = 2131100051;
			
			// aapt resource value: 0x7f060194
			public const int otp_discarded_no_space = 2131100052;
			
			// aapt resource value: 0x7f06018f
			public const int otp_explanation = 2131100047;
			
			// aapt resource value: 0x7f060190
			public const int otp_hint = 2131100048;
			
			// aapt resource value: 0x7f060196
			public const int otps_pending = 2131100054;
			
			// aapt resource value: 0x7f060197
			public const int otpsecret_hint = 2131100055;
			
			// aapt resource value: 0x7f0600c5
			public const int pass_filename = 2131099845;
			
			// aapt resource value: 0x7f060053
			public const int password_access_prefs = 2131099731;
			
			// aapt resource value: 0x7f06001e
			public const int password_access_prefs_key = 2131099678;
			
			// aapt resource value: 0x7f0600c6
			public const int password_title = 2131099846;
			
			// aapt resource value: 0x7f06000a
			public const int permission_desc = 2131099658;
			
			// aapt resource value: 0x7f06005f
			public const int please_activate_keyboard = 2131099743;
			
			// aapt resource value: 0x7f0600ef
			public const int please_note = 2131099887;
			
			// aapt resource value: 0x7f0600c8
			public const int progress_create = 2131099848;
			
			// aapt resource value: 0x7f0600ca
			public const int progress_title = 2131099850;
			
			// aapt resource value: 0x7f06011b
			public const int protection = 2131099931;
			
			// aapt resource value: 0x7f060146
			public const int rate_app = 2131099974;
			
			// aapt resource value: 0x7f0600f1
			public const int regular_expression = 2131099889;
			
			// aapt resource value: 0x7f0600cb
			public const int remember_keyfile_summary = 2131099851;
			
			// aapt resource value: 0x7f0600cc
			public const int remember_keyfile_title = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int remove_from_filelist = 2131099853;
			
			// aapt resource value: 0x7f0600ce
			public const int rijndael = 2131099854;
			
			// aapt resource value: 0x7f0600cf
			public const int root = 2131099855;
			
			// aapt resource value: 0x7f0600d0
			public const int rounds = 2131099856;
			
			// aapt resource value: 0x7f0600d1
			public const int rounds_explaination = 2131099857;
			
			// aapt resource value: 0x7f0600d2
			public const int rounds_hint = 2131099858;
			
			// aapt resource value: 0x7f060011
			public const int rounds_key = 2131099665;
			
			// aapt resource value: 0x7f0600d5
			public const int saving_database = 2131099861;
			
			// aapt resource value: 0x7f0600dc
			public const int search_hint = 2131099868;
			
			// aapt resource value: 0x7f0600de
			public const int search_in = 2131099870;
			
			// aapt resource value: 0x7f0600d7
			public const int search_label = 2131099863;
			
			// aapt resource value: 0x7f0600fa
			public const int search_options = 2131099898;
			
			// aapt resource value: 0x7f0600dd
			public const int search_results = 2131099869;
			
			// aapt resource value: 0x7f060051
			public const int security_prefs = 2131099729;
			
			// aapt resource value: 0x7f06001f
			public const int security_prefs_key = 2131099679;
			
			// aapt resource value: 0x7f0600e0
			public const int select_group_then_add = 2131099872;
			
			// aapt resource value: 0x7f0600df
			public const int select_other_entry = 2131099871;
			
			// aapt resource value: 0x7f060174
			public const int select_storage_type = 2131100020;
			
			// aapt resource value: 0x7f060047
			public const int short_app_name = 2131099719;
			
			// aapt resource value: 0x7f060049
			public const int short_app_name_nonet = 2131099721;
			
			// aapt resource value: 0x7f06004d
			public const int show_kill_app = 2131099725;
			
			// aapt resource value: 0x7f06000e
			public const int show_kill_app_key = 2131099662;
			
			// aapt resource value: 0x7f06004e
			public const int show_kill_app_summary = 2131099726;
			
			// aapt resource value: 0x7f0600d8
			public const int show_password = 2131099864;
			
			// aapt resource value: 0x7f0600da
			public const int sort_db = 2131099866;
			
			// aapt resource value: 0x7f060016
			public const int sort_key = 2131099670;
			
			// aapt resource value: 0x7f0600d9
			public const int sort_name = 2131099865;
			
			// aapt resource value: 0x7f0600d6
			public const int space = 2131099862;
			
			// aapt resource value: 0x7f0600db
			public const int special = 2131099867;
			
			// aapt resource value: 0x7f0600fd
			public const int start_create = 2131099901;
			
			// aapt resource value: 0x7f0600ff
			public const int start_create_import = 2131099903;
			
			// aapt resource value: 0x7f0600fc
			public const int start_open_file = 2131099900;
			
			// aapt resource value: 0x7f0600fe
			public const int start_open_url = 2131099902;
			
			// aapt resource value: 0x7f060145
			public const int suggest_improvements = 2131099973;
			
			// aapt resource value: 0x7f06016b
			public const int synchronize_database_menu = 2131100011;
			
			// aapt resource value: 0x7f060147
			public const int translate_app = 2131099975;
			
			// aapt resource value: 0x7f0600e2
			public const int twofish = 2131099874;
			
			// aapt resource value: 0x7f0600e3
			public const int underline = 2131099875;
			
			// aapt resource value: 0x7f0600e4
			public const int unsupported_db_version = 2131099876;
			
			// aapt resource value: 0x7f0600e5
			public const int uppercase = 2131099877;
			
			// aapt resource value: 0x7f06018c
			public const int use_key_file = 2131100044;
			
			// aapt resource value: 0x7f0600e9
			public const int version_history = 2131099881;
			
			// aapt resource value: 0x7f0600e8
			public const int version_label = 2131099880;
			
			// aapt resource value: 0x7f0600e6
			public const int warning_read_only = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int warning_unmounted = 2131099879;
			
			// aapt resource value: 0x7f0600bd
			public const int yes = 2131099837;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b001f
			public const int AdditionalStringLayout = 2131427359;
			
			// aapt resource value: 0x7f0b0000
			public const int Base = 2131427328;
			
			// aapt resource value: 0x7f0b0017
			public const int BottomBarActionButton = 2131427351;
			
			// aapt resource value: 0x7f0b0002
			public const int Dialog = 2131427330;
			
			// aapt resource value: 0x7f0b0013
			public const int EditEntryButton = 2131427347;
			
			// aapt resource value: 0x7f0b0007
			public const int ElementText = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int ElementTextLarge = 2131427336;
			
			// aapt resource value: 0x7f0b0006
			public const int ElementTextSmall = 2131427334;
			
			// aapt resource value: 0x7f0b000f
			public const int ElementTextTitle = 2131427343;
			
			// aapt resource value: 0x7f0b000e
			public const int EntryFieldHeader = 2131427342;
			
			// aapt resource value: 0x7f0b0010
			public const int EntryItem = 2131427344;
			
			// aapt resource value: 0x7f0b0014
			public const int ExtraFieldHeader = 2131427348;
			
			// aapt resource value: 0x7f0b000b
			public const int GroupAndEntryHeader = 2131427339;
			
			// aapt resource value: 0x7f0b0009
			public const int GroupLabel = 2131427337;
			
			// aapt resource value: 0x7f0b0004
			public const int GroupText = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int GroupTextLarge = 2131427333;
			
			// aapt resource value: 0x7f0b0003
			public const int GroupTextSmall = 2131427331;
			
			// aapt resource value: 0x7f0b0012
			public const int InfoHeader = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int MinusButton = 2131427345;
			
			// aapt resource value: 0x7f0b0001
			public const int NoTitleBar = 2131427329;
			
			// aapt resource value: 0x7f0b0015
			public const int PaddedContainer = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int PaddedElement = 2131427350;
			
			// aapt resource value: 0x7f0b001a
			public const int TextAppearance_EditEntry = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int TextAppearance_EditEntry_LabelSmall = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int TextAppearance_EditEntry_Small = 2131427352;
			
			// aapt resource value: 0x7f0b001b
			public const int TextAppearance_EditEntry_Value = 2131427355;
			
			// aapt resource value: 0x7f0b001e
			public const int TextAppearance_Help = 2131427358;
			
			// aapt resource value: 0x7f0b001c
			public const int TextAppearance_SmallHeading = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int TextAppearance_SubElement = 2131427357;
			
			// aapt resource value: 0x7f0b000a
			public const int WhiteOnBlack = 2131427338;
			
			// aapt resource value: 0x7f0b000c
			public const int WhiteOnBlackSmall = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int WhiteOnDarkSmall = 2131427341;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int preferences = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int searchable = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int searchable_offline = 2131034114;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Kp2aShortHelpView = new int[] {
					16843087,
					2130771968};
			
			// aapt resource value: 0
			public const int Kp2aShortHelpView_android_text = 0;
			
			// aapt resource value: 1
			public const int Kp2aShortHelpView_help_text = 1;
			
			public static int[] TextWithHelp = new int[] {
					16843087,
					2130771968};
			
			// aapt resource value: 0
			public const int TextWithHelp_android_text = 0;
			
			// aapt resource value: 1
			public const int TextWithHelp_help_text = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
