#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("keepass2android.Resource", IsApplication=true)]

namespace keepass2android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			KeePassLib2Android.Resource.String.library_name = keepass2android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080002
			public const int clipboard_timeout_options = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int clipboard_timeout_values = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int cred_remember_modes = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int list_size_options = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int list_size_values = 2131230721;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070004
			public const int TanExpiresOnUse_default = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int keyfile_default = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int maskpass_default = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int omitbackup_default = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int sort_default = 2131165186;
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int bg_gray = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int blue_highlight = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int emphasis = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int emphasis2 = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int group = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int group_header_button_pressed = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int icon_background = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int icon_text = 2131034115;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlueButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_new_group = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_new_group_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int device_access_new_account = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int device_access_new_account_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EntryFieldHeaderBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int extra_string_header = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GreenButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int HeaderButtonBackground = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic00 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic01 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic02 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic03 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic04 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic05 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic06 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic07 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic08 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic09 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic10 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic11 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic12 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic13 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic14 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic15 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic16 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic17 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic18 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic19 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic20 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic21 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic22 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic23 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic24 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic25 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic26 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic27 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic28 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic29 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic30 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic31 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic32 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic33 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic34 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic35 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic36 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic37 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic38 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic39 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic40 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic41 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic42 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic43 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic44 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic45 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic46 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic47 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic48 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic49 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic50 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic51 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic52 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic53 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic54 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic55 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic56 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic57 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic58 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic59 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic60 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic61 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic62 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic63 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic64 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic65 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic66 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic67 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic68 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic99_blank = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic_action_eye_open = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_action_search = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_launcher = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_launcher_folder_small = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_launcher_gray = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_menu_view = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int navigation_accept = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int navigation_accept_dark = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int navigation_previous_item = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int navigation_previous_item_dark = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int notify = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int RedButton = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int section_header = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int YellowButton = 2130837596;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000a
			public const int Credit = 2131427338;
			
			// aapt resource value: 0x7f0b0070
			public const int IconGridView = 2131427440;
			
			// aapt resource value: 0x7f0b007d
			public const int QuickUnlock_button = 2131427453;
			
			// aapt resource value: 0x7f0b007e
			public const int QuickUnlock_buttonLock = 2131427454;
			
			// aapt resource value: 0x7f0b007b
			public const int QuickUnlock_label = 2131427451;
			
			// aapt resource value: 0x7f0b007c
			public const int QuickUnlock_password = 2131427452;
			
			// aapt resource value: 0x7f0b0054
			public const int RelativeLayout = 2131427412;
			
			// aapt resource value: 0x7f0b0053
			public const int ScrollView = 2131427411;
			
			// aapt resource value: 0x7f0b0009
			public const int about_button = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int about_title = 2131427328;
			
			// aapt resource value: 0x7f0b0051
			public const int accept_button = 2131427409;
			
			// aapt resource value: 0x7f0b0024
			public const int add_advanced = 2131427364;
			
			// aapt resource value: 0x7f0b0067
			public const int add_entry = 2131427431;
			
			// aapt resource value: 0x7f0b0066
			public const int add_group = 2131427430;
			
			// aapt resource value: 0x7f0b0023
			public const int advanced_container = 2131427363;
			
			// aapt resource value: 0x7f0b0026
			public const int binaries = 2131427366;
			
			// aapt resource value: 0x7f0b0036
			public const int bottom_bar = 2131427382;
			
			// aapt resource value: 0x7f0b0050
			public const int bottom_layout = 2131427408;
			
			// aapt resource value: 0x7f0b0048
			public const int browse_button = 2131427400;
			
			// aapt resource value: 0x7f0b0059
			public const int btn_length12 = 2131427417;
			
			// aapt resource value: 0x7f0b0058
			public const int btn_length16 = 2131427416;
			
			// aapt resource value: 0x7f0b005b
			public const int btn_length6 = 2131427419;
			
			// aapt resource value: 0x7f0b005a
			public const int btn_length8 = 2131427418;
			
			// aapt resource value: 0x7f0b000e
			public const int cancel = 2131427342;
			
			// aapt resource value: 0x7f0b0052
			public const int cancel_button = 2131427410;
			
			// aapt resource value: 0x7f0b008e
			public const int cbCaseSensitive = 2131427470;
			
			// aapt resource value: 0x7f0b008f
			public const int cbExcludeExpiredEntries = 2131427471;
			
			// aapt resource value: 0x7f0b0084
			public const int cbRegEx = 2131427460;
			
			// aapt resource value: 0x7f0b008d
			public const int cbSearchInGroupName = 2131427469;
			
			// aapt resource value: 0x7f0b008a
			public const int cbSearchInNotes = 2131427466;
			
			// aapt resource value: 0x7f0b008b
			public const int cbSearchInOtherStrings = 2131427467;
			
			// aapt resource value: 0x7f0b0089
			public const int cbSearchInPassword = 2131427465;
			
			// aapt resource value: 0x7f0b008c
			public const int cbSearchInTags = 2131427468;
			
			// aapt resource value: 0x7f0b0086
			public const int cbSearchInTitle = 2131427462;
			
			// aapt resource value: 0x7f0b0087
			public const int cbSearchInUrl = 2131427463;
			
			// aapt resource value: 0x7f0b0088
			public const int cbSearchInUsername = 2131427464;
			
			// aapt resource value: 0x7f0b0064
			public const int cb_brackets = 2131427428;
			
			// aapt resource value: 0x7f0b005f
			public const int cb_digits = 2131427423;
			
			// aapt resource value: 0x7f0b005e
			public const int cb_lowercase = 2131427422;
			
			// aapt resource value: 0x7f0b0060
			public const int cb_minus = 2131427424;
			
			// aapt resource value: 0x7f0b0062
			public const int cb_space = 2131427426;
			
			// aapt resource value: 0x7f0b0063
			public const int cb_specials = 2131427427;
			
			// aapt resource value: 0x7f0b0061
			public const int cb_underline = 2131427425;
			
			// aapt resource value: 0x7f0b005d
			public const int cb_uppercase = 2131427421;
			
			// aapt resource value: 0x7f0b004b
			public const int create = 2131427403;
			
			// aapt resource value: 0x7f0b0094
			public const int cred_password = 2131427476;
			
			// aapt resource value: 0x7f0b0095
			public const int cred_remember_mode = 2131427477;
			
			// aapt resource value: 0x7f0b0093
			public const int cred_username = 2131427475;
			
			// aapt resource value: 0x7f0b0078
			public const int default_database = 2131427448;
			
			// aapt resource value: 0x7f0b0030
			public const int delete = 2131427376;
			
			// aapt resource value: 0x7f0b0008
			public const int disclaimer = 2131427336;
			
			// aapt resource value: 0x7f0b0001
			public const int divider1 = 2131427329;
			
			// aapt resource value: 0x7f0b0004
			public const int divider2 = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int divider3 = 2131427335;
			
			// aapt resource value: 0x7f0b0032
			public const int divider_comment = 2131427378;
			
			// aapt resource value: 0x7f0b0079
			public const int enable_quickunlock = 2131427449;
			
			// aapt resource value: 0x7f0b0041
			public const int entry_accessed = 2131427393;
			
			// aapt resource value: 0x7f0b0040
			public const int entry_accessed_label = 2131427392;
			
			// aapt resource value: 0x7f0b0025
			public const int entry_binaries_label = 2131427365;
			
			// aapt resource value: 0x7f0b0021
			public const int entry_comment = 2131427361;
			
			// aapt resource value: 0x7f0b0020
			public const int entry_comment_label = 2131427360;
			
			// aapt resource value: 0x7f0b001f
			public const int entry_confpassword = 2131427359;
			
			// aapt resource value: 0x7f0b001e
			public const int entry_confpassword_label = 2131427358;
			
			// aapt resource value: 0x7f0b0039
			public const int entry_contents = 2131427385;
			
			// aapt resource value: 0x7f0b003d
			public const int entry_created = 2131427389;
			
			// aapt resource value: 0x7f0b003c
			public const int entry_created_label = 2131427388;
			
			// aapt resource value: 0x7f0b0038
			public const int entry_divider2 = 2131427384;
			
			// aapt resource value: 0x7f0b0037
			public const int entry_edit = 2131427383;
			
			// aapt resource value: 0x7f0b002d
			public const int entry_expires = 2131427373;
			
			// aapt resource value: 0x7f0b002c
			public const int entry_expires_checkbox = 2131427372;
			
			// aapt resource value: 0x7f0b002b
			public const int entry_expires_label = 2131427371;
			
			// aapt resource value: 0x7f0b0022
			public const int entry_extra_strings_label = 2131427362;
			
			// aapt resource value: 0x7f0b0033
			public const int entry_icon = 2131427379;
			
			// aapt resource value: 0x7f0b003f
			public const int entry_modified = 2131427391;
			
			// aapt resource value: 0x7f0b003e
			public const int entry_modified_label = 2131427390;
			
			// aapt resource value: 0x7f0b002a
			public const int entry_override_url = 2131427370;
			
			// aapt resource value: 0x7f0b0029
			public const int entry_override_url_label = 2131427369;
			
			// aapt resource value: 0x7f0b001d
			public const int entry_password = 2131427357;
			
			// aapt resource value: 0x7f0b001b
			public const int entry_password_label = 2131427355;
			
			// aapt resource value: 0x7f0b0012
			public const int entry_save = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int entry_save_header = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int entry_scroll = 2131427347;
			
			// aapt resource value: 0x7f0b003a
			public const int entry_table = 2131427386;
			
			// aapt resource value: 0x7f0b0028
			public const int entry_tags = 2131427368;
			
			// aapt resource value: 0x7f0b0027
			public const int entry_tags_label = 2131427367;
			
			// aapt resource value: 0x7f0b0034
			public const int entry_text = 2131427380;
			
			// aapt resource value: 0x7f0b0016
			public const int entry_title = 2131427350;
			
			// aapt resource value: 0x7f0b0014
			public const int entry_title_label = 2131427348;
			
			// aapt resource value: 0x7f0b001a
			public const int entry_url = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int entry_url_label = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int entry_user_name = 2131427352;
			
			// aapt resource value: 0x7f0b0017
			public const int entry_user_name_label = 2131427351;
			
			// aapt resource value: 0x7f0b003b
			public const int extra_strings = 2131427387;
			
			// aapt resource value: 0x7f0b0006
			public const int feedback = 2131427334;
			
			// aapt resource value: 0x7f0b0042
			public const int file_filename = 2131427394;
			
			// aapt resource value: 0x7f0b0043
			public const int file_listtop = 2131427395;
			
			// aapt resource value: 0x7f0b0044
			public const int file_select = 2131427396;
			
			// aapt resource value: 0x7f0b0073
			public const int filename = 2131427443;
			
			// aapt resource value: 0x7f0b0045
			public const int filename_form = 2131427397;
			
			// aapt resource value: 0x7f0b0071
			public const int filename_label = 2131427441;
			
			// aapt resource value: 0x7f0b0072
			public const int filenamescroll = 2131427442;
			
			// aapt resource value: 0x7f0b004c
			public const int fnv_cancel = 2131427404;
			
			// aapt resource value: 0x7f0b001c
			public const int generate_button = 2131427356;
			
			// aapt resource value: 0x7f0b0056
			public const int generate_password_button = 2131427414;
			
			// aapt resource value: 0x7f0b0065
			public const int group_header = 2131427429;
			
			// aapt resource value: 0x7f0b006b
			public const int group_icon = 2131427435;
			
			// aapt resource value: 0x7f0b006d
			public const int group_label = 2131427437;
			
			// aapt resource value: 0x7f0b0068
			public const int group_name = 2131427432;
			
			// aapt resource value: 0x7f0b006c
			public const int group_text = 2131427436;
			
			// aapt resource value: 0x7f0b0005
			public const int homepage = 2131427333;
			
			// aapt resource value: 0x7f0b006a
			public const int icon = 2131427434;
			
			// aapt resource value: 0x7f0b0015
			public const int icon_button = 2131427349;
			
			// aapt resource value: 0x7f0b006e
			public const int icon_image = 2131427438;
			
			// aapt resource value: 0x7f0b006f
			public const int icon_text = 2131427439;
			
			// aapt resource value: 0x7f0b000c
			public const int install_market = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int install_web = 2131427341;
			
			// aapt resource value: 0x7f0b0047
			public const int label_open_by_filename = 2131427399;
			
			// aapt resource value: 0x7f0b0049
			public const int label_open_by_filename_details = 2131427401;
			
			// aapt resource value: 0x7f0b0046
			public const int label_warning = 2131427398;
			
			// aapt resource value: 0x7f0b005c
			public const int length = 2131427420;
			
			// aapt resource value: 0x7f0b0057
			public const int length_label = 2131427415;
			
			// aapt resource value: 0x7f0b0083
			public const int linearLayout1 = 2131427459;
			
			// aapt resource value: 0x7f0b009b
			public const int menu_about = 2131427483;
			
			// aapt resource value: 0x7f0b009a
			public const int menu_app_settings = 2131427482;
			
			// aapt resource value: 0x7f0b0099
			public const int menu_cancel_edit = 2131427481;
			
			// aapt resource value: 0x7f0b009d
			public const int menu_change_master_key = 2131427485;
			
			// aapt resource value: 0x7f0b0097
			public const int menu_goto_url = 2131427479;
			
			// aapt resource value: 0x7f0b0098
			public const int menu_lock = 2131427480;
			
			// aapt resource value: 0x7f0b009c
			public const int menu_search = 2131427484;
			
			// aapt resource value: 0x7f0b009e
			public const int menu_sort = 2131427486;
			
			// aapt resource value: 0x7f0b0096
			public const int menu_toggle_pass = 2131427478;
			
			// aapt resource value: 0x7f0b0069
			public const int ok = 2131427433;
			
			// aapt resource value: 0x7f0b004a
			public const int open = 2131427402;
			
			// aapt resource value: 0x7f0b0091
			public const int pass_conf_password = 2131427473;
			
			// aapt resource value: 0x7f0b0076
			public const int pass_keyfile = 2131427446;
			
			// aapt resource value: 0x7f0b0077
			public const int pass_ok = 2131427447;
			
			// aapt resource value: 0x7f0b0090
			public const int pass_password = 2131427472;
			
			// aapt resource value: 0x7f0b0055
			public const int password = 2131427413;
			
			// aapt resource value: 0x7f0b0074
			public const int password_label = 2131427444;
			
			// aapt resource value: 0x7f0b002f
			public const int protection = 2131427375;
			
			// aapt resource value: 0x7f0b007a
			public const int qu_filename = 2131427450;
			
			// aapt resource value: 0x7f0b000f
			public const int rounds = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int rounds_explaination = 2131427344;
			
			// aapt resource value: 0x7f0b0082
			public const int scrollView1 = 2131427458;
			
			// aapt resource value: 0x7f0b0081
			public const int searchEditText = 2131427457;
			
			// aapt resource value: 0x7f0b0080
			public const int search_button = 2131427456;
			
			// aapt resource value: 0x7f0b0085
			public const int search_in_label = 2131427461;
			
			// aapt resource value: 0x7f0b007f
			public const int search_label = 2131427455;
			
			// aapt resource value: 0x7f0b004f
			public const int start_create = 2131427407;
			
			// aapt resource value: 0x7f0b0092
			public const int start_create_import = 2131427474;
			
			// aapt resource value: 0x7f0b004d
			public const int start_open_file = 2131427405;
			
			// aapt resource value: 0x7f0b004e
			public const int start_open_url = 2131427406;
			
			// aapt resource value: 0x7f0b000b
			public const int text = 2131427339;
			
			// aapt resource value: 0x7f0b002e
			public const int title = 2131427374;
			
			// aapt resource value: 0x7f0b0035
			public const int title_block = 2131427381;
			
			// aapt resource value: 0x7f0b0075
			public const int toggle_password = 2131427445;
			
			// aapt resource value: 0x7f0b0031
			public const int value = 2131427377;
			
			// aapt resource value: 0x7f0b0003
			public const int version = 2131427331;
			
			// aapt resource value: 0x7f0b0002
			public const int version_title = 2131427330;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int browser_install = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int database_settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int entry_edit = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int entry_edit_section = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int entry_list_entry = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int entry_section = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int entry_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int entry_view_contents = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int file_row = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int file_selection = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int file_selection_filename = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int file_selection_no_recent = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int generate_password = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int group_add_entry = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int group_edit = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int group_empty = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int group_header = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int group_list_entry = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int icon = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int icon_picker = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int password = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int QuickUnlock = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int search = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int set_password = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int StartScreenButtons = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int url_credentials = 2130903066;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int entry = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int entry_edit = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int fileselect = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int group = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int password = 2131361796;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001e
			public const int AboutText = 2131099678;
			
			// aapt resource value: 0x7f0600e7
			public const int AskOverwriteBinary = 2131099879;
			
			// aapt resource value: 0x7f0600ea
			public const int AskOverwriteBinary_no = 2131099882;
			
			// aapt resource value: 0x7f0600e8
			public const int AskOverwriteBinary_title = 2131099880;
			
			// aapt resource value: 0x7f0600e9
			public const int AskOverwriteBinary_yes = 2131099881;
			
			// aapt resource value: 0x7f0600eb
			public const int AttachFailed = 2131099883;
			
			// aapt resource value: 0x7f060016
			public const int BinaryDirectory_default = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int BinaryDirectory_key = 2131099669;
			
			// aapt resource value: 0x7f0600d9
			public const int BinaryDirectory_summary = 2131099865;
			
			// aapt resource value: 0x7f0600d8
			public const int BinaryDirectory_title = 2131099864;
			
			// aapt resource value: 0x7f060031
			public const int ClearClipboard = 2131099697;
			
			// aapt resource value: 0x7f06001f
			public const int CreditsText = 2131099679;
			
			// aapt resource value: 0x7f060067
			public const int FileNotFound = 2131099751;
			
			// aapt resource value: 0x7f06007a
			public const int InvalidPassword = 2131099770;
			
			// aapt resource value: 0x7f060084
			public const int MaskedPassword = 2131099780;
			
			// aapt resource value: 0x7f060017
			public const int QuickUnlockDefaultEnabled_key = 2131099671;
			
			// aapt resource value: 0x7f0600d3
			public const int QuickUnlockDefaultEnabled_summary = 2131099859;
			
			// aapt resource value: 0x7f0600d2
			public const int QuickUnlockDefaultEnabled_title = 2131099858;
			
			// aapt resource value: 0x7f0600d7
			public const int QuickUnlockLength_default = 2131099863;
			
			// aapt resource value: 0x7f060018
			public const int QuickUnlockLength_key = 2131099672;
			
			// aapt resource value: 0x7f0600d5
			public const int QuickUnlockLength_summary = 2131099861;
			
			// aapt resource value: 0x7f0600d4
			public const int QuickUnlockLength_title = 2131099860;
			
			// aapt resource value: 0x7f0600d0
			public const int QuickUnlock_button = 2131099856;
			
			// aapt resource value: 0x7f0600d6
			public const int QuickUnlock_fail = 2131099862;
			
			// aapt resource value: 0x7f0600cf
			public const int QuickUnlock_label = 2131099855;
			
			// aapt resource value: 0x7f0600d1
			public const int QuickUnlock_lockButton = 2131099857;
			
			// aapt resource value: 0x7f0600ec
			public const int RecycleBin = 2131099884;
			
			// aapt resource value: 0x7f0600db
			public const int SaveAttachment_Failed = 2131099867;
			
			// aapt resource value: 0x7f0600da
			public const int SaveAttachment_doneMessage = 2131099866;
			
			// aapt resource value: 0x7f060013
			public const int TanExpiresOnUse_key = 2131099667;
			
			// aapt resource value: 0x7f0600c1
			public const int TanExpiresOnUse_summary = 2131099841;
			
			// aapt resource value: 0x7f0600c0
			public const int TanExpiresOnUse_title = 2131099840;
			
			// aapt resource value: 0x7f060019
			public const int UseFileTransactions_key = 2131099673;
			
			// aapt resource value: 0x7f0600e6
			public const int UseFileTransactions_summary = 2131099878;
			
			// aapt resource value: 0x7f0600e5
			public const int UseFileTransactions_title = 2131099877;
			
			// aapt resource value: 0x7f06001c
			public const int about_feedback = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int about_homepage = 2131099677;
			
			// aapt resource value: 0x7f0600ed
			public const int about_twitter = 2131099885;
			
			// aapt resource value: 0x7f060020
			public const int accept = 2131099680;
			
			// aapt resource value: 0x7f0600e1
			public const int add_binary = 2131099873;
			
			// aapt resource value: 0x7f060021
			public const int add_entry = 2131099681;
			
			// aapt resource value: 0x7f0600e2
			public const int add_extra_string = 2131099874;
			
			// aapt resource value: 0x7f060022
			public const int add_group = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int add_group_title = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int algorithm = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int algorithm_colon = 2131099685;
			
			// aapt resource value: 0x7f060007
			public const int algorithm_key = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int app_key = 2131099656;
			
			// aapt resource value: 0x7f060026
			public const int app_name = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int app_timeout = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int app_timeout_key = 2131099657;
			
			// aapt resource value: 0x7f06002a
			public const int app_timeout_summary = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int application = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int application_settings = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int brackets = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int browser_intall_text = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int building_search_idx = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int cancel = 2131099696;
			
			// aapt resource value: 0x7f0600c5
			public const int caseSensitive = 2131099845;
			
			// aapt resource value: 0x7f060032
			public const int clipboard_timeout = 2131099698;
			
			// aapt resource value: 0x7f06001a
			public const int clipboard_timeout_default = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int clipboard_timeout_key = 2131099658;
			
			// aapt resource value: 0x7f060033
			public const int clipboard_timeout_summary = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int copy_password = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int copy_username = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int creating_db_key = 2131099702;
			
			// aapt resource value: 0x7f0600e4
			public const int credentials_dialog_title = 2131099876;
			
			// aapt resource value: 0x7f060037
			public const int current_group = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int current_group_root = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int database = 2131099705;
			
			// aapt resource value: 0x7f0600e3
			public const int database_loaded_quickunlock_enabled = 2131099875;
			
			// aapt resource value: 0x7f06000b
			public const int db_key = 2131099659;
			
			// aapt resource value: 0x7f06003a
			public const int decrypting_db = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int decrypting_entry = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int default_checkbox = 2131099708;
			
			// aapt resource value: 0x7f060000
			public const int default_file_path = 2131099648;
			
			// aapt resource value: 0x7f0600ac
			public const int default_username = 2131099820;
			
			// aapt resource value: 0x7f060014
			public const int default_username_key = 2131099668;
			
			// aapt resource value: 0x7f0600ad
			public const int default_username_summary = 2131099821;
			
			// aapt resource value: 0x7f06003d
			public const int digits = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int disclaimer_formal = 2131099710;
			
			// aapt resource value: 0x7f060001
			public const int donate_url = 2131099649;
			
			// aapt resource value: 0x7f06003f
			public const int ellipsis = 2131099711;
			
			// aapt resource value: 0x7f0600ce
			public const int enable_quickunlock = 2131099854;
			
			// aapt resource value: 0x7f060040
			public const int enter_filename = 2131099712;
			
			// aapt resource value: 0x7f0600cc
			public const int enter_filename_details_create = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int enter_filename_details_create_import = 2131099853;
			
			// aapt resource value: 0x7f0600ca
			public const int enter_filename_details_file = 2131099850;
			
			// aapt resource value: 0x7f0600cb
			public const int enter_filename_details_url = 2131099851;
			
			// aapt resource value: 0x7f060041
			public const int entry_accessed = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int entry_and_or = 2131099714;
			
			// aapt resource value: 0x7f060052
			public const int entry_binaries = 2131099730;
			
			// aapt resource value: 0x7f060043
			public const int entry_cancel = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int entry_comment = 2131099716;
			
			// aapt resource value: 0x7f060047
			public const int entry_confpassword = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int entry_created = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int entry_expires = 2131099721;
			
			// aapt resource value: 0x7f060051
			public const int entry_extra_strings = 2131099729;
			
			// aapt resource value: 0x7f06004a
			public const int entry_keyfile = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int entry_modified = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int entry_override_url = 2131099718;
			
			// aapt resource value: 0x7f06004c
			public const int entry_password = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int entry_save = 2131099725;
			
			// aapt resource value: 0x7f060045
			public const int entry_tags = 2131099717;
			
			// aapt resource value: 0x7f06004e
			public const int entry_title = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int entry_url = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int entry_user_name = 2131099728;
			
			// aapt resource value: 0x7f060053
			public const int error_arc4 = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int error_can_not_handle_uri = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int error_could_not_create_group = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int error_could_not_create_parent = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int error_database_exists = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int error_database_settings = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int error_failed_to_launch_link = 2131099737;
			
			// aapt resource value: 0x7f06005b
			public const int error_file_not_create = 2131099739;
			
			// aapt resource value: 0x7f06005a
			public const int error_filename_required = 2131099738;
			
			// aapt resource value: 0x7f06005c
			public const int error_invalid_db = 2131099740;
			
			// aapt resource value: 0x7f0600dc
			public const int error_invalid_expiry_date = 2131099868;
			
			// aapt resource value: 0x7f06005d
			public const int error_invalid_path = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int error_no_name = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int error_nopass = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int error_out_of_memory = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int error_pass_gen_type = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int error_pass_match = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int error_rounds_not_number = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int error_rounds_too_large = 2131099748;
			
			// aapt resource value: 0x7f0600dd
			public const int error_string_key = 2131099869;
			
			// aapt resource value: 0x7f060065
			public const int error_title_required = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int error_wrong_length = 2131099750;
			
			// aapt resource value: 0x7f0600c3
			public const int excludeExpiredEntries = 2131099843;
			
			// aapt resource value: 0x7f0600de
			public const int field_name = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int field_value = 2131099871;
			
			// aapt resource value: 0x7f060068
			public const int file_browser = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int generate_password = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int group = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int hint_comment = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int hint_conf_pass = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int hint_generated_password = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int hint_group_name = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int hint_keyfile = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int hint_length = 2131099760;
			
			// aapt resource value: 0x7f060072
			public const int hint_login_pass = 2131099762;
			
			// aapt resource value: 0x7f060075
			public const int hint_override_url = 2131099765;
			
			// aapt resource value: 0x7f060071
			public const int hint_pass = 2131099761;
			
			// aapt resource value: 0x7f060076
			public const int hint_tags = 2131099766;
			
			// aapt resource value: 0x7f060073
			public const int hint_title = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int hint_url = 2131099764;
			
			// aapt resource value: 0x7f060077
			public const int hint_username = 2131099767;
			
			// aapt resource value: 0x7f060002
			public const int homepage = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int homepage_short = 2131099651;
			
			// aapt resource value: 0x7f060078
			public const int install_from_market = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int install_from_website = 2131099769;
			
			// aapt resource value: 0x7f06007b
			public const int invalid_algorithm = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int invalid_db_sig = 2131099772;
			
			// aapt resource value: 0x7f060004
			public const int issues = 2131099652;
			
			// aapt resource value: 0x7f06007d
			public const int keyfile_does_not_exist = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int keyfile_is_empty = 2131099774;
			
			// aapt resource value: 0x7f06000d
			public const int keyfile_key = 2131099661;
			
			// aapt resource value: 0x7f0600c2
			public const int kp2a_findUrl = 2131099842;
			
			// aapt resource value: 0x7f06007f
			public const int length = 2131099775;
			
			// aapt resource value: 0x7f060028
			public const int library_name = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int list_size_default = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int list_size_key = 2131099664;
			
			// aapt resource value: 0x7f060081
			public const int list_size_summary = 2131099777;
			
			// aapt resource value: 0x7f060080
			public const int list_size_title = 2131099776;
			
			// aapt resource value: 0x7f060082
			public const int loading_database = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int lowercase = 2131099779;
			
			// aapt resource value: 0x7f06000e
			public const int maskpass_key = 2131099662;
			
			// aapt resource value: 0x7f060086
			public const int maskpass_summary = 2131099782;
			
			// aapt resource value: 0x7f060085
			public const int maskpass_title = 2131099781;
			
			// aapt resource value: 0x7f060087
			public const int menu_about = 2131099783;
			
			// aapt resource value: 0x7f06008c
			public const int menu_app_settings = 2131099788;
			
			// aapt resource value: 0x7f060088
			public const int menu_change_key = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int menu_copy_pass = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int menu_copy_user = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int menu_create = 2131099787;
			
			// aapt resource value: 0x7f06008d
			public const int menu_db_settings = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int menu_delete = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int menu_donate = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int menu_edit = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int menu_hide_password = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int menu_homepage = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int menu_lock = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int menu_open = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int menu_rename = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int menu_search = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int menu_url = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int minus = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int never = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int no_keys = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int no_results = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int no_url_handler = 2131099804;
			
			// aapt resource value: 0x7f060005
			public const int oi_filemanager_market = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int oi_filemanager_web = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int omitbackup_key = 2131099663;
			
			// aapt resource value: 0x7f06009f
			public const int omitbackup_summary = 2131099807;
			
			// aapt resource value: 0x7f06009e
			public const int omitbackup_title = 2131099806;
			
			// aapt resource value: 0x7f06009d
			public const int open_recent = 2131099805;
			
			// aapt resource value: 0x7f0600a0
			public const int pass_filename = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int password_title = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int progress_create = 2131099810;
			
			// aapt resource value: 0x7f0600a3
			public const int progress_title = 2131099811;
			
			// aapt resource value: 0x7f0600e0
			public const int protection = 2131099872;
			
			// aapt resource value: 0x7f0600bf
			public const int regular_expression = 2131099839;
			
			// aapt resource value: 0x7f0600a4
			public const int remember_keyfile_summary = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int remember_keyfile_title = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int remove_from_filelist = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int rijndael = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int root = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int rounds = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int rounds_explaination = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int rounds_hint = 2131099819;
			
			// aapt resource value: 0x7f06000c
			public const int rounds_key = 2131099660;
			
			// aapt resource value: 0x7f0600ae
			public const int saving_database = 2131099822;
			
			// aapt resource value: 0x7f0600b5
			public const int search_hint = 2131099829;
			
			// aapt resource value: 0x7f0600b7
			public const int search_in = 2131099831;
			
			// aapt resource value: 0x7f0600b0
			public const int search_label = 2131099824;
			
			// aapt resource value: 0x7f0600c4
			public const int search_options = 2131099844;
			
			// aapt resource value: 0x7f0600b6
			public const int search_results = 2131099830;
			
			// aapt resource value: 0x7f060027
			public const int short_app_name = 2131099687;
			
			// aapt resource value: 0x7f0600b1
			public const int show_password = 2131099825;
			
			// aapt resource value: 0x7f0600b3
			public const int sort_db = 2131099827;
			
			// aapt resource value: 0x7f060011
			public const int sort_key = 2131099665;
			
			// aapt resource value: 0x7f0600b2
			public const int sort_name = 2131099826;
			
			// aapt resource value: 0x7f0600af
			public const int space = 2131099823;
			
			// aapt resource value: 0x7f0600b4
			public const int special = 2131099828;
			
			// aapt resource value: 0x7f0600c7
			public const int start_create = 2131099847;
			
			// aapt resource value: 0x7f0600c9
			public const int start_create_import = 2131099849;
			
			// aapt resource value: 0x7f0600c6
			public const int start_open_file = 2131099846;
			
			// aapt resource value: 0x7f0600c8
			public const int start_open_url = 2131099848;
			
			// aapt resource value: 0x7f060012
			public const int timeout_key = 2131099666;
			
			// aapt resource value: 0x7f0600b8
			public const int twofish = 2131099832;
			
			// aapt resource value: 0x7f0600b9
			public const int underline = 2131099833;
			
			// aapt resource value: 0x7f0600ba
			public const int unsupported_db_version = 2131099834;
			
			// aapt resource value: 0x7f0600bb
			public const int uppercase = 2131099835;
			
			// aapt resource value: 0x7f0600be
			public const int version_label = 2131099838;
			
			// aapt resource value: 0x7f0600bc
			public const int warning_read_only = 2131099836;
			
			// aapt resource value: 0x7f0600bd
			public const int warning_unmounted = 2131099837;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090011
			public const int Base = 2131296273;
			
			// aapt resource value: 0x7f090001
			public const int Dialog = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int ElementText = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int ElementTextLarge = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int ElementTextSmall = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int ElementTextTitle = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int EntryFieldHeader = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int EntryItem = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int ExtraFieldHeader = 2131296272;
			
			// aapt resource value: 0x7f09000a
			public const int GroupAndEntryHeader = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int GroupLabel = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int GroupText = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int GroupTextLarge = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int GroupTextSmall = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int NoTitleBar = 2131296256;
			
			// aapt resource value: 0x7f090009
			public const int WhiteOnBlack = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int WhiteOnBlackSmall = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int WhiteOnDarkSmall = 2131296268;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int searchable = 2130968577;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
